#!/usr/bin/env python
import sys
import argparse
from Bio import Phylo

def tree_view(args):
	tree = Phylo.read(args.nwk, "newick")
	Phylo.draw_ascii(tree)

if __name__ == '__main__':
	parser = argparse.ArgumentParser(description="tree view")
	parser.add_argument("nwk", type=argparse.FileType("r"), help=("tree file(newick format)"))

	args = parser.parse_args()

	tree_view(args)
